server:
  port: 8081

spring:
  datasource:
    url: jdbc:mariadb://mariadb:3306/maplekiosk
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  config:
    import: optional:dotenv:.env


jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-minutes: 30
  refresh-token-expiration-days: 7